<a href="https://colab.research.google.com/github/Devraj-prasad07/python-for-data-analysis/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Nupmy
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

Installing Numpy in Colab Notebook

In [ ]:
!pip install numpy

Importing Numpy

In [3]:
import numpy as np

1 Dimension Array

In [22]:
arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


Checking the arr1 Shape

In [23]:
print(arr1.shape)

(5,)


Checking the arr Type

In [4]:
arr = np.array([])
type(arr)

numpy.ndarray

2 Dimension Array with attributes of Numpy Array


In [26]:
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
print(arr2.shape)
print('ndim:', arr2.ndim)
print('size:', arr2.size)
print('dtype:', arr2.dtype)
print('itemsize:', arr2.itemsize)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)
ndim: 2
size: 10
dtype: int64
itemsize: 8


UseCase of arange Fn

In [25]:
np.arange(0,10,2).reshape(1,5),np.arange(0,10,2).reshape(5,1)

(array([[0, 2, 4, 6, 8]]),
 array([[0],
        [2],
        [4],
        [6],
        [8]]))

Numpy Vectorized Operations

In [27]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
print('addition: ', arr1+arr2)
print('subtraction: ', arr1-arr2)
print('multiplication: ', arr1*arr2)
print('division: ', arr1/arr2)
print('modulo: ', arr1%arr2)

addition:  [ 7  9 11 13 15]
subtraction:  [-5 -5 -5 -5 -5]
multiplication:  [ 6 14 24 36 50]
division:  [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
modulo:  [1 2 3 4 5]


Universal Fn

In [28]:
arr = np.array([1,2,3,4,5])
print('square root: ', np.sqrt(arr))
print('exponential: ', np.exp(arr))
print('sine: ', np.sin(arr))
print('cosine: ', np.cos(arr))
print('logarithm: ', np.log(arr))

square root:  [1.         1.41421356 1.73205081 2.         2.23606798]
exponential:  [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
sine:  [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
cosine:  [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
logarithm:  [0.         0.69314718 1.09861229 1.38629436 1.60943791]


Array Slicing and Indexing

In [34]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print('Original array:\n', arr)
print('\nIndividual rows (arr[0], arr[1], arr[2]):\n', arr[0], arr[1], arr[2])
print('\nIndividual elements (arr[0][0], arr[1][0], arr[2][0]):\n', arr[0][0], arr[1][0], arr[2][0])
print('\nIndividual elements (arr[0][1], arr[1][1], arr[2][1]):\n', arr[0][1], arr[1][1], arr[2][1])
print('\nSlicing from a specific row to the end (arr[0:], arr[1:], arr[2:]):\n', arr[0:], arr[1:], arr[2:])
print('\nSlicing specific rows (arr[0:1], arr[1:2], arr[2:3]):\n', arr[0:1], arr[1:2], arr[2:3])

Original array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

Individual rows (arr[0], arr[1], arr[2]):
 [1 2 3 4 5] [ 6  7  8  9 10] [11 12 13 14 15]

Individual elements (arr[0][0], arr[1][0], arr[2][0]):
 1 6 11

Individual elements (arr[0][1], arr[1][1], arr[2][1]):
 2 7 12

Slicing from a specific row to the end (arr[0:], arr[1:], arr[2:]):
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]] [[ 6  7  8  9 10]
 [11 12 13 14 15]] [[11 12 13 14 15]]

Slicing specific rows (arr[0:1], arr[1:2], arr[2:3]):
 [[1 2 3 4 5]] [[ 6  7  8  9 10]] [[11 12 13 14 15]]


Statistical Concepts -- Nomalization

In [37]:
from os.path import normcase
data = np.array([1,2,3,4,5])

## Calualte the mean and standard Deviation
mean = np.mean(data)
std_dev = np.std(data)

## Normalize the Data
normalizedData = (data - mean) / std_dev
print('Normalized Data:', normalizedData)

Normalized Data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [39]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
#Mean
mean = np.mean(data)
print('Mean:', mean)
#Median
median = np.median(data)
print('Median:', median)
#Mode
from scipy import stats
mode = stats.mode(data)
print('Mode:', mode)
#Standard Deviation
std_dev = np.std(data)
print('Standard Deviation:', std_dev)
#Variance
variance = np.var(data)
print('Variance:', variance)

Mean: 5.5
Median: 5.5
Mode: ModeResult(mode=np.int64(1), count=np.int64(1))
Standard Deviation: 2.8722813232690143
Variance: 8.25


Logical Operations

In [40]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
data[(data >= 5) & (data <= 8)]

array([5, 6, 7, 8])